# Site settings
title: Gaussian Process School Colombia, 2014
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2014 Gaussian Process School held at the Universidad Tecnologica de Pereira
baseurl: "/gprs13/" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Mauricio Alvarez, url: "https://sites.google.com/site/maalvarezl/"}
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Mauricio Alvarez, url: "https://sites.google.com/site/maalvarezl/"}
  
  name: Gaussian Process School, Colombia
  location: Universidad Tecnologica de Pereira, Pereira, Colombia
  month: February
  year: 2014
  dates:
  - {date: 11, day: Tuesday, month: February, year: 2014}
  - {date: 12, day: Wednesday, month: February, year: 2014}
  - {date: 13, day: Thursday, month: February, year: 2014}
  - {date: 14, day: Friday, month: February, year: 2014}
  
# Build settings
markdown: kramdown
